/**
 * Engine artifact digests.
 *
 * engine_digest is SHA-256 of the exact bytes of the vendored engine files
 * for that slug (sorted path order, concatenated). Tests recompute from disk
 * and refuse a stale embed. The Worker isolate has no filesystem, so it uses
 * the committed hex; that hex is the digest of those same bytes.
 *
 * Author: Aziel Eliab.
 */
import { sha256Hex } from "../session-core.js";

/** Relative to src/engines/. Only the running engine artifact — not HTTP wrappers. */
export const ENGINE_ARTIFACTS = {
  vibelock: ["vibelock/engine.js"],
  veillock: ["veillock/engine.js"],
  codelock: ["codelock/engine.js"],
  godlock: ["godlock/engine.js"],
  shadowlock: ["shadowlock/engine.js"],
  temporallock: ["temporallock/engine.js"],
  forgereceipts: ["forgereceipts/engine.js"],
  decisiongate: ["decisiongate/engine.js"],
  zsolver: ["zsolver/engine.js"],
  azos: ["azos/engine.js"],
  glossafilter: ["glossafilter/engine.js"],
  miragegrid: ["miragegrid/engine.js"],
  staticclock: ["staticclock/engine.js", "staticclock/data.js"],
  chronolock: ["chronolock/engine.js", "chronolock/data.js"],
  postking: ["postking/engine.js"],
  azclce: ["azclce/engine.js", "azclce/triad.js"],
  ark: ["ark/engine.js"],
  azai: ["azai/engine.js"],
  spectrallock: ["spectrallock/overlay.js"],
  azbot: ["azbot/engine.js"],
  employeelock: ["employeelock/engine.js"],
  foldlock: ["foldlock/codec.js"],
  whistlelock: ["whistlelock/engine.js"],
  trajectorylock: ["trajectorylock/engine.js"],
  mialock: ["mialock/doe-match.js", "mialock/doe-notices.js", "mialock/queries.js", "mialock/search-modes.js"],
  azieltether: ["azieltether/engine.js"],
  "aziel-corpus": ["aziel-corpus/engine.js"],
};

/**
 * SHA-256 hex of each slug's artifact bytes. Regenerated by scripts/hash-engines.mjs.
 * Do not invent a digest — recompute from the files.
 */
export const ENGINE_DIGESTS = {
  "vibelock": "12b960bdfe739bad4509fa087932b2f89b39b1eb2d3997b4b646a8f60d13bc9d",
  "veillock": "b7114d83e33d9f3c05427110115b798c23209eb2716a6431b6bcbe4a613fd464",
  "codelock": "cdeacc8ed400760227248c5946d07528e2dfaf4542a40f20cb9961833d199c0b",
  "godlock": "6b9076ca8e4aa63e6c81deb40f102f55f8769a7c10f0b8347605903f7df93f54",
  "shadowlock": "0176d18d8517ef02b391821b1fd1ae428591543ea1c812c9785d832714281f61",
  "temporallock": "467cabd5102fe40fe00c1e3c7352e8dfa9c197232deae24a59ad10ecf001840c",
  "forgereceipts": "aa78349f801b730a89d65653de81d1cb33a59ee5f024e7177161b2bb50048eb5",
  "decisiongate": "06775e3c95d74eb8d42d01321a61dc350dc7b62c93673062f9f41d781af3bef0",
  "zsolver": "8667a3d95f6063b77cb0ab0ff629192b6c5036d95762adb20f3c90f4b73a977f",
  "azos": "c143a47fd7d5e629b4ae731e872ef191a2f7967ce697d37f55ad03bda0091bce",
  "glossafilter": "4d876f57934277eb56119a8041f2787fee45121b87eeb9c1f054b1d05b8dd3e3",
  "miragegrid": "c755b9a47dbb24a13dda9b913edda4ab220006ee50bcbc167a3ae01b302ddafd",
  "staticclock": "8d590c265b0be3ab7f5ea15d7a8530b5bb532fa079f1a474e33257fae79ce6df",
  "chronolock": "983960a4369c5255959e9ad53fa8085911578e2dfcce1bdd9c58166d1466bd78",
  "postking": "d25f9e81813816349e5e1c2064227ae193b9e3480cbea128a359a929a8232307",
  "azclce": "0b0451fce91436e04ccf52337c392a20b68c87dfc200514fe760450a666e20c9",
  "ark": "69d29bd079754df6450b8882b6f86c445ac7f1f490e2c150ff4716d00bf6d3b6",
  "azai": "96bd3281c17db65645accde17d1f0ab19be72c58a1ca45a4abd75d28839dc61e",
  "spectrallock": "8d8ff93b6e312e790bffd5cfe47afa09056e7ac5839d89f8df5ea010ba27c9c6",
  "azbot": "7963fd4ca7c94e117ae8456e04e21950f390bf68b07ecffd85aca7d717c9d1db",
  "employeelock": "886e90395752e7dcb5458a6ee501c34858a18574623b2e542513b4faa96e1d90",
  "foldlock": "1034d5924b88878918986abe260338b0aff0117bc6f9c4d4a01a41d843cfa0a8",
  "whistlelock": "f585b20e1dfc0321e432ba04299d91d1708ae3b6f2ac78c85db5c61a63a4a6f8",
  "trajectorylock": "318ec9bf93b699376caca613c77447b113f1c741b14b102357433f0024afc119",
  "mialock": "d65c53dbc46d500f6d02c8975e42bf95a22000c15db4776d5fdef58904d32a5c",
  "azieltether": "adb57573ee23e7c97567fc05f916f1fd65f2265128bd9ec3d1dca08e47c2d791",
  "aziel-corpus": "a33ad0018f479f954bfd0e5881f871af04bf9b39f2565db2e0cdb591f6fc8085",
};

export function trueEngineSlugs() {
  return Object.keys(ENGINE_ARTIFACTS).sort();
}

export function isTrueEngineSlug(slug) {
  return Boolean(ENGINE_ARTIFACTS[String(slug || "").toLowerCase()]);
}

export async function digestConcatenated(parts) {
  const encoder = new TextEncoder();
  let total = 0;
  const chunks = [];
  for (const part of parts) {
    const bytes = typeof part === "string" ? encoder.encode(part) : part;
    chunks.push(bytes);
    total += bytes.byteLength;
  }
  const out = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) {
    out.set(chunk, offset);
    offset += chunk.byteLength;
  }
  const hex = await sha256Hex(out);
  out.fill(0);
  return hex;
}

export async function digestArtifactBytes(fileBytesByPath) {
  const paths = Object.keys(fileBytesByPath).sort();
  const parts = [];
  for (const path of paths) {
    parts.push(new TextEncoder().encode(path + "\n"));
    parts.push(fileBytesByPath[path]);
    parts.push(new TextEncoder().encode("\n"));
  }
  return digestConcatenated(parts);
}

export function embeddedDigest(slug) {
  const key = String(slug || "").toLowerCase();
  return ENGINE_DIGESTS[key] || null;
}
