/**
 * Engine artifact digests.
 *
 * engine_digest is SHA-256 of the exact bytes of the vendored engine files
 * for that slug (sorted path order, concatenated). Tests recompute from disk
 * and refuse a stale embed. The Worker isolate has no filesystem, so it uses
 * the committed hex; that hex is the digest of those same bytes.
 *
 * Author: Aziel Eliab.
 */
import { sha256Hex } from "../session-core.js";

/** Relative to src/engines/. Only the running engine artifact — not HTTP wrappers. */
export const ENGINE_ARTIFACTS = {
  vibelock: ["vibelock/engine.js"],
  veillock: ["veillock/engine.js"],
  codelock: ["codelock/engine.js"],
  godlock: ["godlock/engine.js"],
  shadowlock: ["shadowlock/engine.js"],
  temporallock: ["temporallock/engine.js"],
  forgereceipts: ["forgereceipts/engine.js"],
  decisiongate: ["decisiongate/engine.js"],
  zsolver: ["zsolver/engine.js"],
  azos: ["azos/engine.js", "azos/session.js"],
  glossafilter: ["glossafilter/engine.js"],
  miragegrid: ["miragegrid/engine.js"],
  staticclock: ["staticclock/engine.js", "staticclock/data.js"],
  chronolock: ["chronolock/engine.js", "chronolock/data.js"],
  postking: ["postking/engine.js"],
  azclce: ["azclce/engine.js", "azclce/triad.js"],
  ark: ["ark/engine.js"],
  azai: ["azai/engine.js"],
  spectrallock: ["spectrallock/overlay.js"],
  azbot: ["azbot/engine.js"],
  employeelock: ["employeelock/engine.js"],
  foldlock: ["foldlock/codec.js"],
  whistlelock: ["whistlelock/engine.js"],
  trajectorylock: ["trajectorylock/engine.js"],
  mialock: ["mialock/doe-match.js", "mialock/doe-notices.js", "mialock/queries.js", "mialock/search-modes.js"],
  azieltether: ["azieltether/engine.js"],
  peacelock: ["peacelock/engine.js"],
  azmail: ["azmail/engine.js", "azmail/guard.js"],
  azbrowser: ["azbrowser/engine.js"],
  aznet: ["aznet/engine.js"],
  azhub: ["azhub/engine.js"],
  azinterface: ["azinterface/engine.js"],
  "aziel-corpus": ["aziel-corpus/engine.js", "aziel-corpus/jeeves.js", "aziel-corpus/jeeves-eggs.js", "aziel-corpus/tip-pack.js"],
  "4dmap": ["4dmap/aznews-feed.js", "4dmap/aznews-gazetteer.js", "4dmap/aznews-geo.js", "4dmap/aznews-live.js", "4dmap/aznews-outlets.js", "4dmap/aznews-pins.js", "4dmap/aznews-sky.js", "4dmap/aznews-source.js", "4dmap/aznews-weather.js", "4dmap/aznews.js", "4dmap/engine.js", "4dmap/lattice.js", "4dmap/ops.js", "4dmap/product-card.js"],
  azcoherence: ["azcoherence/engine.js"],
  embryolock: ["embryolock/engine.js"],
  azchat: ["azchat/engine.js"],
  zkattest: ["zkattest/engine.js"],
  mmconsensus: ["mmconsensus/engine.js"],
  toolbench: ["toolbench/engine.js"],
  azvpn: ["azvpn/engine.js"],
};

/**
 * SHA-256 hex of each slug's artifact bytes. Regenerated by scripts/hash-engines.mjs.
 * Do not invent a digest — recompute from the files.
 */
export const ENGINE_DIGESTS = {
  "vibelock": "bf35c9e62ae2717bac039d74ff81be7af57be4c454a418b1cc4abffee9d08d5a",
  "veillock": "b7114d83e33d9f3c05427110115b798c23209eb2716a6431b6bcbe4a613fd464",
  "codelock": "cdeacc8ed400760227248c5946d07528e2dfaf4542a40f20cb9961833d199c0b",
  "godlock": "6b9076ca8e4aa63e6c81deb40f102f55f8769a7c10f0b8347605903f7df93f54",
  "shadowlock": "0176d18d8517ef02b391821b1fd1ae428591543ea1c812c9785d832714281f61",
  "temporallock": "fa1ce89d3201c3a4d00f46da1253418b11e98fb50414cd1c65517e2282ed6b5e",
  "forgereceipts": "c72efccfedd1411bef4ee8637f409c31580aaae46515ca64770648d4d01b99ed",
  "decisiongate": "4e86778de3d0d7795611a7b3d29d7c734fa808a03e1e22e93bc3b694910bf172",
  "zsolver": "8667a3d95f6063b77cb0ab0ff629192b6c5036d95762adb20f3c90f4b73a977f",
  "azos": "2a264494946e23e44d8ab1f649ee54bd7f72012923c1d3e9f10d39f9300edc93",
  "glossafilter": "4d876f57934277eb56119a8041f2787fee45121b87eeb9c1f054b1d05b8dd3e3",
  "miragegrid": "cea1854f20a807360d68c3b223343088abe09941ae77e406fd45ee4fe1d1126c",
  "staticclock": "7d6da0f2ef3fdbeedc2e96f5676a58847a8cd09dc94053009814dfa4fd282fb3",
  "chronolock": "672a014671a63660b0538ef6d08485ebf1141489aa68bf6173995bc34fd4d4ab",
  "postking": "d25f9e81813816349e5e1c2064227ae193b9e3480cbea128a359a929a8232307",
  "azclce": "f1854d7bd0396761f942b54b78f42c66d4c04e4956189de79371ed67b9ae2b69",
  "ark": "69d29bd079754df6450b8882b6f86c445ac7f1f490e2c150ff4716d00bf6d3b6",
  "azai": "435766c8de739bff706cda75a4e496726ed43de60224241cd6d98ca640efcebd",
  "spectrallock": "16281860ab0787f2485ea2530fbbcecf968009da3ae1c4f2b6e689a15a9ad586",
  "azbot": "909872259998d5ee9e276158b86194f704d40796588e5cc52d5ca15a86909456",
  "employeelock": "886e90395752e7dcb5458a6ee501c34858a18574623b2e542513b4faa96e1d90",
  "foldlock": "1034d5924b88878918986abe260338b0aff0117bc6f9c4d4a01a41d843cfa0a8",
  "whistlelock": "f585b20e1dfc0321e432ba04299d91d1708ae3b6f2ac78c85db5c61a63a4a6f8",
  "trajectorylock": "7f536c9d148515d9b4e578c558361255db226cd5e3066daee1eee68209bfe3a7",
  "mialock": "d65c53dbc46d500f6d02c8975e42bf95a22000c15db4776d5fdef58904d32a5c",
  "azieltether": "adb57573ee23e7c97567fc05f916f1fd65f2265128bd9ec3d1dca08e47c2d791",
  "peacelock": "291437f64ba15338d6358e6d2e657870619b19133430be3574d458b8db469a66",
  "azmail": "06a6cba66c12090415cec91a06890de0b32edfa86e5631bcd2a78d0f9b5d27ec",
  "azbrowser": "f27b40c284a748de8c290742bf9aa3deda716893af8963d97707dca28dd65b48",
  "aznet": "d089fb7636b27186ee5f3ec2468cc20d74ca5e5af65e77ebaa3492788b1751cf",
  "azhub": "dc8848353c0db397b9b0503446ad8dcb14212162776b24278071559bd2e83d81",
  "azinterface": "7418c2bbf3c8fe4921f05f0e9f1aed2d2486f983d8feba985fe462018794972c",
  "aziel-corpus": "e122bae90a8426451861c11e39829f9ed000b0d0793a7e9260e6ee68c93c4ab8",
  "4dmap": "03b5c908434c5f6eb914853eea5426e37892e1edfa7bb8f73b7ebe13eee41641",
  "azcoherence": "f04dfa4af332a1c04bd7319a8f48cee3e9adec3877d198ea703ee6187790cfc5",
  "embryolock": "bc7f6119a4bf6910b5be50cabe19bf4a2e35ac60408b5713e94878bd4e0074f3",
  "azchat": "9b63fc0adcbb65318fbad7fd6aaf39b6f44edc5ff41696571457a5bd765ec5c5",
  "zkattest": "bb3831ed980be81dce15fda1dbb471a7458c91feb907a410a86173003df1c84a",
  "mmconsensus": "9624f144b1eacfc11cf86fe45ed83acb6f65fa324629668510c55f1fcabe6fe7",
  "toolbench": "888385a251997a21f07368d71eff0bb56ed5f68871a6f84900ab62f28c8da33c",
  "azvpn": "2d3d27cf49df95d5a041a55d4fd75d20c65ed167a5c170ef6f363ec15599b776",
};

export function trueEngineSlugs() {
  return Object.keys(ENGINE_ARTIFACTS).sort();
}

export function isTrueEngineSlug(slug) {
  return Boolean(ENGINE_ARTIFACTS[String(slug || "").toLowerCase()]);
}

export async function digestConcatenated(parts) {
  const encoder = new TextEncoder();
  let total = 0;
  const chunks = [];
  for (const part of parts) {
    const bytes = typeof part === "string" ? encoder.encode(part) : part;
    chunks.push(bytes);
    total += bytes.byteLength;
  }
  const out = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) {
    out.set(chunk, offset);
    offset += chunk.byteLength;
  }
  const hex = await sha256Hex(out);
  out.fill(0);
  return hex;
}

export async function digestArtifactBytes(fileBytesByPath) {
  const paths = Object.keys(fileBytesByPath).sort();
  const parts = [];
  for (const path of paths) {
    parts.push(new TextEncoder().encode(path + "\n"));
    parts.push(fileBytesByPath[path]);
    parts.push(new TextEncoder().encode("\n"));
  }
  return digestConcatenated(parts);
}

export function embeddedDigest(slug) {
  const key = String(slug || "").toLowerCase();
  return ENGINE_DIGESTS[key] || null;
}
