#!/usr/bin/env python3
"""Build src/engines/4dmap/aznews-regions.js (AZNEWS-GEO-1.1 region gazetteer).

Sources (public domain): Natural Earth 10m
  ne_10m_admin_1_states_provinces (admin-1 name, iso_a2, latitude, longitude label point)
  ne_10m_geography_regions_polys  (named land regions, centroid of the largest part)
  ne_10m_geography_marine_polys   (named seas/gulfs/bays, centroid of the largest part)
Usage: python3 scripts/build-aznews-regions.py <dir-with-NE-files>
Author: Aziel Eliab.
"""
import json, sys, re, shapefile
d = sys.argv[1]
GENERIC = {"Central","North","South","East","West","Northern","Southern","Eastern","Western","Capital","Coast","Lakes","Islands","Upper","Lower","Centre","Center","Interior","Federal","National","Border","River","Lake","Valley","Mountain","Plateau","Highlands","Littoral","Kingston","Male","Victoria","Georgia","Chad","Nice","Reading","Mobile","Split","Of","Orange","Delta","Santa","San","Saint","Grand","Mount","Lima","Pest","Para","Amazonas","Alba","Nord","Sud","Est","Ouest","Centro","Norte","Sur","Oriental","Occidental","York","Kent","Essex","Moray","Down","Antrim","Bath","Wells","Ely","Sale","Mayo","Clare","Cork","Kerry","Meath","Laois","Louth","Gold","Rich","Green","Bay","Ash","March","May","June","August","Chester","Bristol","Durham","Lincoln","Sherman","Lancaster","Jackson","Washington","Franklin","Hamilton","Madison","Jefferson","Kings","Queens","Carlow","Asia","Europe","Africa","Ocean","Sea","Gulf","Ram","Ra"}
def ok(n):
    return n and len(n) >= 4 and n not in GENERIC and not re.search(r"[0-9()]", n)
def clean(n):
    n = re.sub(r"\s+", " ", (n or "").strip())
    n = n.replace("Mts.", "Mountains").replace("Pen.", "Peninsula").replace("Plat.", "Plateau")
    if n.isupper(): n = " ".join(w.capitalize() if w not in ("OF","DE","DEL") else w.lower() for w in n.split())
    return n
def centroid(shape):
    pts, parts = shape.points, list(shape.parts) + [len(shape.points)]
    best = None
    for i in range(len(parts) - 1):
        ring = pts[parts[i]:parts[i+1]]
        a = cx = cy = 0.0
        for (x0, y0), (x1, y1) in zip(ring, ring[1:] + ring[:1]):
            c = x0*y1 - x1*y0; a += c; cx += (x0+x1)*c; cy += (y0+y1)*c
        if a and (best is None or abs(a) > abs(best[0])): best = (a, cx/(3*a), cy/(3*a))
    return (round(best[2], 3), round(best[1], 3)) if best else None
admin = []
r = shapefile.Reader(dbf=open(f"{d}/ne_10m_admin_1_states_provinces.dbf", "rb"))
for x in r.records():
    for key in ("name", "name_en"):
        n = clean(x[key])
        if ok(n) and x["iso_a2"] and len(x["iso_a2"]) == 2 and x["latitude"] is not None:
            admin.append([n, x["iso_a2"], round(x["latitude"], 3), round(x["longitude"], 3), (x["type_en"] or "region")[:24]])
seen = set(); A = []
for row in admin:
    k = (row[0], row[1])
    if k in seen: continue
    seen.add(k); A.append(row)
named = []
for f, rank in (("ne_10m_geography_regions_polys", 4), ("ne_10m_geography_marine_polys", 4)):
    r = shapefile.Reader(f"{d}/{f}")
    fields = [y[0].lower() for y in r.fields[1:]]
    for sr in r.iterShapeRecords():
        rec = dict(zip(fields, sr.record))
        if (rec.get("scalerank") or 9) > rank: continue
        if (rec.get("featurecla") or "").lower() in ("island", "island group", "pen/cape"): continue
        n = clean(rec.get("name_en") or rec.get("name"))
        c = centroid(sr.shape)
        if ok(n) and c: named.append([n, c[0], c[1], (rec.get("featurecla") or "region").lower()[:16]])
ns = set(); N = []
for row in named:
    if row[0] in ns: continue
    ns.add(row[0]); N.append(row)
out = f"""/**
 * AZNews region gazetteer (AZNEWS-GEO-1.1, generated by scripts/build-aznews-regions.py, do not hand-edit).
 * Source: Natural Earth 10m (public domain), https://www.naturalearthdata.com/
 *   GAZ_ADMIN1: ne_10m_admin_1_states_provinces -> [name, ISO2, label lat, label lon, type]
 *   GAZ_NAMED:  ne_10m_geography_regions_polys + ne_10m_geography_marine_polys (scalerank <= 4)
 *               -> [name, centroid lat, centroid lon, feature class]
 * Author: Aziel Eliab.
 */
export const REGIONS_SOURCE = Object.freeze({{ name: "Natural Earth", url: "https://www.naturalearthdata.com/", license: "public domain", files: ["ne_10m_admin_1_states_provinces", "ne_10m_geography_regions_polys", "ne_10m_geography_marine_polys"], built: "2026-10-10" }});
export const GAZ_ADMIN1 = {json.dumps(A, ensure_ascii=False, separators=(",", ":"))};
export const GAZ_NAMED = {json.dumps(N, ensure_ascii=False, separators=(",", ":"))};
"""
open("src/engines/4dmap/aznews-regions.js", "w").write(out)
print(len(A), len(N), len(out))
